---
title: "suSiE test"
author: "Jui-Shan Lin"
date: "5/11/2021"
output: pdf_document
---

### Setting up environment. 

```{r}
##Only for first time setting up. 
# package that was used in susie
#install.packages("mixsqp")

# package that allow us to install github package
#install.packages('devtools')
```

```{r}
library("mixsqp")
devtools::install_github("stephenslab/susieR")
library(susieR)
```

## First play it with simple regression. 
```{r}
set.seed(1)
n <- 1000
p <- 1000
beta <- rep(0,p)
#other beta = 0, only 1,2,300,400 = 1
beta[c(1,2,300,400)] <-1

X <- matrix(rnorm(n*p), nrow=n, ncol=p)
y <- X %*% beta + rnorm(n)
res <- susie(X,y, L=10) ## L 這裡指的最多可以有幾個非0的coefficient

par(mfrow=c(2,2))

plot(coef(res)[-1],pch = 20) ##除了第一項的常數項

plot(y,predict(res),pch = 20)


# Test with simulated data 
data("N3finemapping")
attach(N3finemapping)
dim(Y) ## there are two replicates in this Y.
b <- true_coef[,1]
plot(b, pch=22, ylab="effect size")
which(b != 0)
```


### Gathering information from summary statistics
```{r}
sumstats <- univariate_regression(N3finemapping$X,Y[,1])  # we now only focus on the first of the two replicates. 
z_scores <- sumstats$betahat /sumstats$sebetahat
susie_plot(z_scores, y = "z", b = b) #the argument b is here set to highlight true effect in red.
```


###  Finally we are starting with fine mapping
```{r}
# print 95% credible set (default)
fitted <- susie(N3finemapping$X,Y[,1], 
                L = 10,
                estimate_residual_variance = TRUE, 
                estimate_prior_variance = FALSE,
                scaled_prior_variance = 0.1,
                verbose = TRUE
                )


print(fitted $sets)

```
```{r}
# How about setting the coverage from 0.95 to 0.9?
sets <- susie_get_cs(fitted, X = N3finemapping$X,
                     coverage = 0.9,
                     min_abs_corr = 0.1)
print(sets)
# You can easily tell that with lower coverage, L2 is also smaller, with higher correlation. 
```

### Posterior inclusion probabilities
```{r}
susie_plot(fitted, y = "PIP", b=b)



i  <- fitted$sets$cs[[3]]
z3 <- cbind(i,z_scores[i],fitted$pip[i])
colnames(z3) <- c('position', 'z-score', 'PIP')
z3[order(z3[,2], decreasing = TRUE),]

```


#### reference
https://stephenslab.github.io/susieR/articles/finemapping.html
