---
title: "annotation_weight"
author: "Teresa Lin"
date: "9/12/2022"
output:
  pdf_document: default
 
---


```{r, include = FALSE}
library(ggplot2)
library(lattice)
library(dplyr)
library(stringr)
library(tidyr)
library(ggstance)
library(jtools)
library(tibble)
library(tidyverse)
library(cowplot)
```
```{r}
## load weight for every anno (diff chr has diff weights)
load_weight <- function(chr){
  kunkle = read.csv(paste('/gpfs/commons/home/tlin/output/kunkle/kunkle_fixed_0224/kunkle.annot_coeff_ridge.',chr,'.txt', sep = ''), sep = '\t', col.names = c('annotations', 'Kunkle'))
  bellenguez = read.csv(paste('/gpfs/commons/home/tlin/output/bellenguez/bellenguez_fixed_0224/bellenguez.annot_coeff_ridge.',chr,'.txt', sep = ''), sep = '\t',col.names = c('annotations', 'Bellenguez'))
  wightman = read.csv(paste('/gpfs/commons/home/tlin/output/wightman/wightman_fixed_0224/wightman_all.annot_coeff_ridge.',chr,'.txt', sep = ''), sep = '\t',col.names = c('annotations', 'Wightman'))
  jansen = read.csv(paste('/gpfs/commons/home/tlin/output/jansen/jansen.annot_coeff_ridge.',chr,'.txt', sep = ''), sep = '\t',col.names = c('annotations', 'Jansen'))
  df_list <- list(kunkle, bellenguez, wightman, jansen)
  annotation <- df_list %>% reduce(full_join, by='annotations')
  annotation = pivot_longer(annotation, cols=c('Kunkle','Bellenguez', 'Wightman','Jansen'), names_to='sumstat')  ## make it easier for visualization
  annotation$sumstat = factor(annotation$sumstat,levels = c("Kunkle","Bellenguez","Wightman","Jansen"))
  return(annotation)
}

sort_bellenguez_weight <- function(df){
  sort = df %>% 
    subset(sumstat == 'Bellenguez') %>%
    arrange(value) %>%
    pull(annotations)
  
  return(sort)
}


plot_bar <- function(df,title){
  ggplot(df, aes(value, annotations, fill = sumstat))+
  geom_bar(stat = "identity", position = 'dodge', alpha = 0.5) + ylab('')+xlab('weight')+ggtitle(title) +theme_minimal()
}

plot_head_tail <- function(pt1, pt2, chr, label =  c("top 10 annotations", "bottom 10 annotations")){
  figure <- plot_grid(pt1, pt2,
                    labels =label,
                    ncol = 1, nrow = 2)
  print(figure)
}

```

```{r}
## get df_anno names 
dl_anno <- c(colnames(read.csv2(gzfile("/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations/combined_AD_annotations_polyfun/combined_AD_annotations_polyfun_22.annot.gz"), sep = '\t')),
    colnames(read.csv2(gzfile("/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations/brain_H3K4me3/merged_annotations_ukb/brain_H3K4me3_seq_chr22.annot.gz"), sep = '\t')),
    colnames(read.csv2(gzfile("/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/annotations/brain_H3K27ac/merged_annotations_ukb/brain_H3K27ac_seq_chr22.annot.gz"), sep = '\t')))
remove = c('CHR','SNP','BP','A1','A2')
dl_anno = str_replace(setdiff(dl_anno, remove), "X", "")
```

```{r,fig.align="center", echo = FALSE,fig.width = 12}

for (i in 1:22){
  weights = load_weight(i)
  bellenguez_sort_anno = sort_bellenguez_weight(weights)
  pt1 = plot_bar(weights[which(weights$annotations %in% (bellenguez_sort_anno[1:10])),], paste('chr',i))
  pt2 = plot_bar(weights[which(weights$annotations %in% (tail(bellenguez_sort_anno,10))),], '')
  plot_head_tail(pt1, pt2)

}


```
```{r,fig.align="center", echo = FALSE,fig.width = 17}
for (i in 1:22){
  weights = load_weight(i)
  
  pt1 = plot_bar(weights[which(weights$annotations %in% dl_anno),], paste('chr',i))
  pt2 = plot_bar(subset(weights[which(weights$annotations %in% dl_anno),], sumstat!='Kunkle'), paste('chr',i))
  pt1 = pt1 +coord_flip()+ theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1))+scale_fill_manual(values = c('lightblue','lightslateblue','lightpink','gray'))
  pt2 = pt2 +coord_flip()+ theme(axis.text.x = element_text(angle = 60))+scale_fill_manual(values = c('lightslateblue','lightpink','gray'))
  plot_head_tail(pt1, pt2, label='')

}
```

