---
title: "ADSP PRS"
author: "Teresa Lin"
date: "7/18/2022"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(lattice)
library(dplyr)
library(stringr)
library(tidyr)
library(ggstance)
library(jtools)
library(tibble)
library(readr)
library(cowplot)
library(pROC)
library(modEvA)  # psuedo rsquare
library(boot)
```

## Functions to process PRS file. 
```{r}
pre_process <- function(df){
  df<- read.csv(df,sep = '\t', header=T,fill = T)
  if("age_covariate" %in% colnames(df))  ## because there were two files with different column names for phenotype merging.
  {
    colnames(df)[which(names(df) == 'age_covariate')] <- 'Age'
    colnames(df)[which(names(df) == 'AD_status_final')] <- 'Diagnosis'
  }
  df$Age <- as.numeric(as.character(df$Age))
  print(paste("original=",  dim(df)[1], "rows"))
  df <- df %>%
    filter(Diagnosis != -1 & Age >= 65)
  print(paste("filtered=",  dim(df)[1], "rows"))
  return(df)
}

```

## Load PRS result from different summary statistics and methods. 
```{r, include=FALSE}
### polyfun_pred ----
kunkle_polypred <- pre_process('/gpfs/commons/home/tlin/output/prs/polypred/kunkle/kunkle_polypred.tsv')
bellenguez_polypred <- pre_process("/gpfs/commons/home/tlin/output/prs/bellenguez/fixed_0224/bellenguez_fixed_0224.tsv")
wightman_polypred <- pre_process('/gpfs/commons/home/tlin/output/prs/polypred/wightman/fixed_0224.prs.tsv')

## After fixing convergence issue (The only "MAX_SNP_PER_LOCUS" is 3.)
bellenguez_polypred <- pre_process('/gpfs/commons/home/tlin/output/prs/polypred/bellenguez/fixed_0224_polypred.prs')

## SuSiE
kunkle_susie <- pre_process("/gpfs/commons/home/tlin/output/prs/polypred/kunkle/susie.prs.tsv")
bellenguez_susie <- pre_process("/gpfs/commons/home/tlin/output/prs/bellenguez_susie/bellenguez_susie_prs_PC.tsv")



### plink ----
## Kunkle
kunkle_APOE <- pre_process("/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/APOE.tsv")
kunkle_withoutAPOE_qc <- pre_process("/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/remove_APOE_qc_on_variant_sumstat.tsv")
kunkle_withoutAPOE <- pre_process("/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/remove_APOE.tsv")

kunkle_cT <- pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/kunkle_no_qc.tsv')
kunkle_qc <- pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/kunkle_qc.tsv')
kunkle_qc_target <-pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/kunkle_qc_on_target.tsv')
kunkle_qc_base <- pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/kunkle_qc_on_base.tsv')


kunkle_qc_variant <- pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/kunkle_qc_on_variant_update.tsv')
kunkle_qc_individual <- pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/kunkle_qc_on_individual_update.tsv')
kunkle_qc_variant_sumstat <- pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/qc_on_variant_sumstat.tsv')
kunkle_new_beta <- pre_process('/gpfs/commons/home/tlin/output/prs/kunkle/fixed_0224/new_beta_noqc.tsv')
kunkle_new_beta <- kunkle_new_beta[-31]


## Bellenguez
bellenguez_cT <- pre_process('/gpfs/commons/home/tlin/output/prs/bellenguez/fixed_0224/bellenguez_no_qc.tsv')
bellenguez_qc <- pre_process('/gpfs/commons/home/tlin/output/prs/bellenguez/fixed_0224/bellenguez_qc.tsv')
bellenguez_qc_on_target <- pre_process('/gpfs/commons/home/tlin/output/prs/bellenguez/fixed_0224/bellenguez_qc_on_target.tsv')
bellenguez_qc_on_base <- pre_process('/gpfs/commons/home/tlin/output/prs/bellenguez/fixed_0224/bellenguez_qc_on_base.tsv')
## Before fixing convergence issue


## Wightman

### others ----
## new plink
kunkle_adsp <- pre_process('/gpfs/commons/home/tlin/output/prs/new_plink/kunkle/kunkle_ADSP.tsv')
bellenguez_adsp <- pre_process('/gpfs/commons/home/tlin/output/prs/new_plink/bellenguez/bellenguez_ADSP.tsv')
wightman_adsp <- pre_process('/gpfs/commons/home/tlin/output/prs/new_plink/wightman/wightman_ADSP.tsv')


kunkle_adsp_qc <- pre_process('/gpfs/commons/home/tlin/output/prs/new_plink/kunkle/kunkle_ADSP_qc_all.tsv')
bellenguez_adsp_qc <- pre_process('/gpfs/commons/home/tlin/output/prs/new_plink/bellenguez/bellenguez_ADSP_qc_all.tsv')
wightman_adsp_qc <- pre_process('/gpfs/commons/home/tlin/output/prs/new_plink/wightman/wightman_ADSP_qc_all.tsv')




```

## Analysis of QC target file (ADSP plink file)
```{r, include=FALSE}
filtered <- subset(wightman_adsp, !IID %in%  wightman_adsp_qc$IID)
summary(filtered[c('cohort', 'Diagnosis','final_population')])
summary(wightman_adsp[c('cohort', 'Diagnosis','final_population')])

```

```{r, echo = FALSE, fig.height=5, fig.width=15}
par(mfrow=c(1,3))
draw_pie_chart <- function(df, col, name=' '){
 if (col != 'Diagnosis' && col != 'AD_status_final'){
  df[[col]]<-factor(df[[col]])
 }
  pie_labels <- paste(names(summary(df[[col]])),'\n', "(", round(summary(df[[col]])/sum(summary(df[[col]])) * 100,2), "%)")
  pie(summary(df[[col]]), main= name, labels = pie_labels,cex=1,radius=0.75, cex.main=1.5)
}

for (col in c('cohort', 'final_population')){
 draw_pie_chart(wightman_adsp, col, name= 'Before QC')
 draw_pie_chart(filtered, col, name= "Individual been filtered out")
 draw_pie_chart(wightman_adsp_qc, col, name= "After QC")
}


```

## Check the if the individual being filtered out in genotyping file has duplicates in phenotyping file
```{r}
remove=read.csv("/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/ADSP_vcf/17K_final/annotated_filtered_hg37/plink/ADSP_qc_all/ADSP_qc_all.irem", sep = '\t',header = FALSE)
phenotype = read.csv("/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/ADSP_vcf/compact_filtered_vcf_16906/phenotype_data_10_28_2021/all_phenotypes_unique_ancestry_subset.tsv", sep = '\t')
colnames(remove) <- c('FID','IID')
```


```{r, echo = FALSE, fig.height=5, fig.width=15}
phenotype_should_remove =phenotype[phenotype$SampleID %in% remove$IID,]
par(mfrow=c(1,3))
draw_pie_chart(phenotype_should_remove, 'Duplicate_SUBJID', name= 'Duplicated SUBJID')
draw_pie_chart(phenotype_should_remove, 'cohort', name= 'Cohort')
draw_pie_chart(phenotype_should_remove, 'AD_status_final', name= 'Diagnosis')
write.table(phenotype_should_remove, file='/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/ADSP_vcf/17K_final/annotated_filtered_hg37/plink/ADSP_qc_all/phenotype_should_remove.tsv', quote = F, sep = '\t')
```
## Including Plots